app.security.api-key=dev-api-key
spring.datasource.url=jdbc:mariadb://localhost:3306/fiveplayer
spring.datasource.username=jad_efrei_five_2526
spring.datasource.password=jad_efrei_five_2526
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
