@startuml

package "group-02-manage-match" {
  [Match Service]
}

package "group-03-record-match" {
  [Record Match Service]
}

package "group-04-summarize-match" {
  [Summarize Match Service]
}

package "group-05-manage-player" {
  [Player Service]
}

package "group-06-manage-team" {
  [Team Service]
}

package "Field Management Context" {
  [Field Service]
  [Field DB]
}
interface "Field API" as FieldAPI
interface "Event Bus" as EventBus

[Match Service] --> FieldAPI: use

FieldAPI - [Field Service]
[Field Service] --> [Field DB]
[Field Service] --> EventBus: publish

[Record Match Service] ..> [Match Service]: indirect
[Summarize Match Service] ..> [Match Service]: indirect

note right of [Field Service]
Owns only:
- fields
- field statuses
- reservations
end note

@enduml
