@startuml

package "Backoffice Context" {
  [Admin Service]
}
interface "Admin API" as AdminAPI

package "Booking Context" {
  [Booking Service]
}
interface "Booking API" as BookingAPI

package "Manage Field Context" {
  [Terrain Service]
  [Terrain DB]
}
interface "Terrain API" as TerrainAPI
interface "Event Bus" as EventBus

AdminAPI - [Admin Service]
[Admin Service] --> TerrainAPI: use

BookingAPI - [Booking Service]
[Booking Service] --> TerrainAPI: use

TerrainAPI - [Terrain Service]
[Terrain Service] --> [Terrain DB]
[Terrain Service] --> EventBus: publish

@enduml
