micronaut.application.name=manage_match
  
datasources.default.url=jdbc:postgresql://151.80.234.144:5432/prod_manage_match
datasources.default.driverClassName=org.postgresql.Driver
datasources.default.username=match_api
datasources.default.password=ukPRB5cr3qqDP8
datasources.default.dialect=POSTGRES
  
services.field.url=
services.record.url=
services.team.url=

jackson.serialization.write-dates-as-timestamps=false