#!/usr/bin/env bash
set -euo pipefail

ADMIN_USER="${MARIADB_ADMIN_USER:-fivefield_admin}"
ADMIN_PASSWORD="${MARIADB_ADMIN_PASSWORD:-fivefield_admin}"
APP_USER="${MARIADB_APP_USER:-fivefield}"
APP_PASSWORD="${MARIADB_APP_PASSWORD:-fivefield}"
DATABASE="${MARIADB_DATABASE:-manage_field}"

mariadb --protocol=socket -uroot -p"${MARIADB_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${DATABASE}\`
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${ADMIN_USER}'@'%' IDENTIFIED BY '${ADMIN_PASSWORD}';
ALTER USER '${ADMIN_USER}'@'%' IDENTIFIED BY '${ADMIN_PASSWORD}';

CREATE USER IF NOT EXISTS '${APP_USER}'@'%' IDENTIFIED BY '${APP_PASSWORD}';
ALTER USER '${APP_USER}'@'%' IDENTIFIED BY '${APP_PASSWORD}';

GRANT ALL PRIVILEGES ON \`${DATABASE}\`.* TO '${ADMIN_USER}'@'%' WITH GRANT OPTION;

REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${APP_USER}'@'%';
GRANT USAGE ON *.* TO '${APP_USER}'@'%';

FLUSH PRIVILEGES;
SQL
