spring:
  application:
    name: manage-team
  profiles:
    default: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://jeanaymeric.hd.free.fr:8601/fiveteam
    username: jad_efrei_five_2526
    password: ${MANAGE_TEAM_DB_PASSWORD}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8080

app:
  console:
    enabled: true


