spring.application.name=api-manage-match

spring.datasource.url=jdbc:postgresql://151.80.234.144:5432/prod_manage_match
spring.datasource.username=manage_match
spring.datasource.password=manage_match

service.field.url=http://127.0.0.1:5000
service.team.url=http://127.0.0.1:5000

match.outbound.notify-urls.started[0]=http://127.0.0.1:5000/events/match-started
match.outbound.notify-urls.ended[0]=http://127.0.0.1:5000/events/match-ended