@startuml

package "Player Context" {
  [Player DB]
  [Player Service]
}
interface "Player API" as PlayerAPI

package "Character Context" {
  [Character Service]
  [Character DB]
  [ACL Player Adapter]
}
interface "Character API" as CharacterAPI

package "Inventory Context" {
  [Inventory Service]
  [Inventory DB]
}
interface "Inventory API" as InventoryAPI

CharacterAPI - [Character Service]
[Character Service] --> [Character DB]
[Character Service] --> [ACL Player Adapter]

InventoryAPI - [Inventory Service]
[Inventory Service] --> [Inventory DB]

PlayerAPI -- [Player Service]
[Player Service] -> [Player DB]
[ACL Player Adapter] --> PlayerAPI: use

@enduml
