@startuml
|Swimlane1|
start
:Action 1;
:object 1; <<object>>
if (test) then (yes)
  :Action 2;
else (no)
  :Action3; <<sendSignal>>
  end
endif
|Swimlane2|
:object 2; <<object>>
:Action 4;
stop
@enduml